import Link from 'next/link'
import Layout from '../components/Layout'
import { getAllPosts } from '../prisma/post'

export default function Index({ posts }) {
  return (
    <Layout>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{' '}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {posts.map((post) => (
          <li key={post.id}>
            <Link
              as={`/posts/${post.slug}`}
              href={`/posts/[slug]`}
            >
              <a>{post.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </Layout>
  )
}

export const getStaticProps = async () => {
  var posts = await getAllPosts()

  posts = posts.map(elt => ({
    id: elt.id,
    slug: elt.slug,
    title: elt.title,
  }))

  return { props: { posts } }
}
